version: "3.5"

services:
    nginx:
        image: nginx:latest
        container_name: nginx2
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/logs/nginx:/var/log/nginx

    php-fpm:
        build:
            context: docker/php-fpm
        container_name: php-fpm2
        environment:
            XDEBUG_CONFIG: "remote_host=172.31.0.1"
            PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql
        container_name: mysql2
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always

        environment:
            MYSQL_DATABASE: Products
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root

